[package]
name = "vanity"
version = "0.5.0"
edition = "2021"
authors = [
    "Cavey Cool <caveycool@gmail.com>",
    "Magnetar Fields <0xMAGNETAR@proton.me>",
]
license = "MIT OR Apache-2.0"
description = "A *bLaZinGlY fAsT* tool for grinding vanity addresses on Solana"

[features]
gpu = ["cc"]
deploy = ["solana-rpc-client"]
server = ["axum", "tokio", "serde", "serde_json", "tower", "tower-http", "uuid", "chrono", "dotenvy"]
default = []

[profile.release]
lto = "fat"
codegen-units = 1


[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
fd_bs58 = "0.1.0"
logfather = "0.2.6"
num-format = "0.4.4"
rand = "0.8.5"
rayon = "1.10.0"
sha2 = "0.10.8"
solana-pubkey = { version = "2.1.0", features = ["sha2"] }
solana-rpc-client = { version = "2.1.0", optional = true }
solana-sdk = { version = "2.1.0", optional = true }
axum = { version = "0.7", optional = true }
tokio = { version = "1.0", features = ["full"], optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
tower = { version = "0.4", optional = true }
tower-http = { version = "0.5", features = ["cors", "trace"], optional = true }
uuid = { version = "1.0", features = ["v4"], optional = true }
chrono = { version = "0.4", features = ["serde"], optional = true }
dotenvy = { version = "0.15", optional = true }

[build-dependencies]
cc = { version = "1.0.98", optional = true }
